[build]
  functions = "functions"

[dev]
  publish = "dist"

[[redirects]]
  to="/.netlify/functions/api/:splat"
  from="/*"
  status=200

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"